{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if (include "grafana.createAdminSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-admin
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: grafana
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- $previous := lookup "v1" "Secret" (include "common.names.namespace" .) (printf "%s-admin" (include "common.names.fullname" .)) | mergeOverwrite (dict "data" dict) }}
  GF_SECURITY_ADMIN_PASSWORD: {{ coalesce .Values.admin.password (dig "data" "GF_SECURITY_ADMIN_PASSWORD" "" $previous | b64dec) (now | unixEpoch | sha256sum | b64enc | trunc 10) | b64enc | quote }}
{{- end }}
