{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: keycloak
  {{- if or .Values.auth.annotations .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.merge" (dict "values" (list .Values.auth.annotations .Values.commonAnnotations) "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- $previous := lookup "v1" "Secret" (include "common.names.namespace" .) (include "common.names.fullname" . | trunc 63 | trimSuffix "-") }}
  admin-password: {{ coalesce .Values.auth.adminPassword (dig "data" "admin-password" "" $previous | b64dec) (now | unixEpoch | sha256sum | b64enc | trunc 10) | b64enc | quote }}
{{- end }}
